Budget app
codehass/Budget-app pull request #1
Opened 2023-04-28 12:26 UTC by codehass

# Budget app pull request: 

- Splash screen

- [ ] A simple page with the name of your app (yes, you need to choose one), and links to the sign up and log in pages.

- Sign up and log in pages

- [ ] The user should be able to register in the app with full name, email and password (all mandatory).
- [ ] The user can log into the app using email and password.
- [ ] If the user is not logged in, they can't access pages that require the user to be logged in (all the pages described below).

- Home page (categories page)

When the user logs in, they are presented with the categories page.
For each category, the user can see their name, icon and the total amount of all the transactions that belongs to that category.
When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
There is a button "add a new category" at the bottom that brings the user to the page to create a new category.
- Transactions page

- [ ] For a given category, the list of transactions is presented, ordered by the most recent.
- [ ] At the top of the page the user could see the total amount for the category (sum of all of the amounts of the transactions in that category).
- [ ] There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.
- [ ] When the user clicks on the "Back" button (<), the user navigates to the home page.

- "Add a new category" page

- [ ] The user fills out a form to create a new category, indicating their name and icon (both mandatory).
- [ ] The user clicks (or taps) the "Save" button to create the new category, and is taken to the home page on success.
- [ ] When the user clicks on the "Back" button (<), the user navigates to the home page.

- "Add a new transaction" page

- [ ] The user fills out a form to create a new transaction with:
- [ ] name (mandatory)
- [ ] amount (mandatory)
- [ ] categories (mandatory at least one)
- [ ] The user click (or taps) the "Save" button to create the new transaction, and is taken to the transactions page for that category.
- [ ] When the user clicks on the "Back" button (<), the user navigates to the transactions page for that category.

- Testing requirements

- [ ] Create unit and integration tests for all the most important components of your RoR application.

2023-04-28 13:45 UTC, ShadyShawkat requested changes
## Hi @codehass, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight
- All linters are passing ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 13:45 UTC, ShadyShawkat commented on README.md
> +I would like to thank Microverse for providing us with reading materials that aided us to during the project development
- [x] Please make sure to give appropriate credit to the author of the original design, as per [this](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#:~:text=Original%20design%20idea,of%20your%20project.) requirement.

2023-04-28 13:45 UTC, ShadyShawkat commented on config/routes.rb
> +end
- [x] Please make sure to implement a "Splash Screen" and set it as a root route, as per [this](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#:~:text=Splash%20screen,log%20in%20pages.) requirement. There're guidelines for the style of the "Splash Screen" that you can follow. 

![image](https://user-images.githubusercontent.com/62290545/235152988-e360ee2c-ca6e-43de-be42-a9127bd22316.png)

2023-04-28 13:45 UTC, ShadyShawkat commented on app/views/devise/registrations/new.html.erb
> +</div>
- Please make sure to stick to the original design as much as possible, which includes:
   - [ ] Using the same typography and font style as per [this](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#:~:text=Typography%3A%20font%20face%2C%20size%20and%20weight.) requirement.
   - [ ] Changing the positioning of the "Submit" button to be in the nav which is then named "Next".
   - [ ] Editing the style of the inputs to look more like the original template.
   - [ ] Adding a "left arrow" icon to the left part of the nav which acts as a back button to match the given template.
   - [ ] Using the same color in the nav and the text color as well, as per [this](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#:~:text=guidelines%2C%20including%3A-,Colors.,-Typography%3A%20font%20face) requirement.
   - [ ] Changing the background of the page to match the one in the design.
   
(This goes for all other forms as well even if they don't have a direct style guideline, as per [this](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#:~:text=NOTE%3A%20In%20these%20design%20guidelines%20there%20are%20several%20UIs%20that%20you%20won%27t%20need%20for%20this%20exercise%3B%20also%2C%20some%20pages%20are%20not%20given%20a%20design%20and%20you%20will%20create%20them%20following%20the%20design%20guidelines%20of%20the%20other%20pages.) requirement)
| Your design | Original design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/62290545/235155462-cec028b8-1c4c-4327-8af3-9225b0f1817a.png) | ![image](https://user-images.githubusercontent.com/62290545/235155597-22d2f993-9767-448e-b94e-afe12ad50d64.png) |

2023-04-28 13:45 UTC, ShadyShawkat commented on app/views/groups/index.html.erb
> +	</div>
- [ ] Please adjust the styling of this button to look more like the original design.
- [ ] The same goes for the "Add a new transaction" button.

| Your design | Original design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/62290545/235160400-53512556-6dab-4c12-b650-1fb616805d2a.png) | ![image](https://user-images.githubusercontent.com/62290545/235160463-21f97a59-2419-47de-a18c-c8893fed155c.png) |

2023-04-28 13:45 UTC, ShadyShawkat commented on app/views/groups/index.html.erb
> +		<%= link_to 'Add a new category', new_user_group_path(current_user) %>
- [ ] Kindly use the same color of the design for the button, as you have the colors in the design.

![image](https://user-images.githubusercontent.com/62290545/235161085-3ca1af0e-649d-44b7-b9da-d04d17a95267.png)

2023-04-29 04:56 UTC, uwadonat approved these changes
## Hi @codehass,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 
### Highlights
- Amazing design ✔️
- Professional readme file ✔️
- Good commit history  ✔️
![approval1](https://user-images.githubusercontent.com/65860678/235284292-72bfbc47-cf12-4473-a24f-b3ed40fe342c.gif)

# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-04-29 11:15 UTC, merged